services:
  cms: 
    build: 
      dockerfile: Dockerfile
      context: .
    working_dir: /var/www/cms
    volumes: 
      - .:/var/www/cms
      - /var/www/cms/node_modules
    ports:
      - 5005:3001